version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  backend-build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          app-dir: ~/project/backend
          steps:
            - run: npm install
            - run: npm test
workflows:
    backend:
      jobs:
        - backend-build-and-test